spring:
  profiles:
active: development

spring:
  profiles: development
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: nood-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
defaultZone: http://nood-discovery:8761/eureka/
