server:
  port: 8764
logging:
  level:
    root: DEBUG
eureka:
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    preferIpAddress: true
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
  client:
    registerWithEureka: true
    fetchRegistry: false
    healthcheck:
          enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    allow-request-override: true
    suffix: .html

