server:
  port: 8764

##默认前缀
spring:
   mvc:
     view:
        prefix: /
        suffix: .html
logging:
  level:
    root: INFO
eureka:
  instance:
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    preferIpAddress: true
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
  client:
    registerWithEureka: true
    fetchRegistry: false
    healthcheck:
          enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

